---
name: Egg-Release-DBIC
version: 0.02
author:
  - 'Masatoshi Mizuno E<lt>lusheE<64>cpan.orgE<gt>'
abstract: lib/Egg/Release/DBIC.pm
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DBIx::Class: 0.08009
  DBIx::Class::Schema::Loader: 0.03
  Egg::Release: 3.00
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Egg::Helper::Model::DBIC:
    file: lib/Egg/Helper/Model/DBIC.pm
    version: 3.00
  Egg::Model::DBIC:
    file: lib/Egg/Model/DBIC.pm
    version: 3.00
  Egg::Model::DBIC::Schema:
    file: lib/Egg/Model/DBIC/Schema.pm
    version: 3.00
  Egg::Model::DBIC::handler:
    file: lib/Egg/Model/DBIC.pm
  Egg::Plugin::DBIC:
    file: lib/Egg/Plugin/DBIC.pm
    version: 0.01
  Egg::Release::DBIC:
    file: lib/Egg/Release/DBIC.pm
    version: 0.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
